-- FAZ UMA CONSULTA GIGANTESCA, MAS FUNCIONA

SELECT * FROM TVENDEDOR V, TENDERECO E
WHERE V.ID_ENDERECO = E.ID;

-- INNER JOIN, SÓ TRAZ O QUE TEM EM AMBAS AS TABELAS

SELECT * FROM TVENDEDOR V
INNER JOIN TENDERECO E
ON V.ID_ENDERECO = E.ID;

-- FORMA MAIS LEGÍVEL

SELECT NOME, LOCALIDADE FROM TVENDEDOR V
INNER JOIN TENDERECO E
ON V.ID_ENDERECO = E.ID;

-- MAIS ELEGANTE, USANDO ALIAS

SELECT V.NOME, E.LOCALIDADE FROM TVENDEDOR V
INNER JOIN TENDERECO E
ON V.ID_ENDERECO = E.ID;

------------------------

SELECT * FROM TALIMENTICIO A
INNER JOIN TPRODUTO P
ON A.ID = P.ID;

SELECT * FROM TELETRONICO E
INNER JOIN TPRODUTO P
ON E.ID = P.ID;
